### ISSUE TITLE
Base32 conversion fails to strip padding chars ('=')

### ISSUE THREAD

**Issue by ScottIsAFool** [Yortw/Yort.Otp#1]
If your OTP secret has equals signs at the end as padding, the base32 function should be stripping that before it tries encoding it.

**Comment by Yortw** [comment]
Hi Scott,

Thanks for reporting this, I appreciate it. Hopefully I'll get time to look at this sometime this weekend, perhaps tomorrow afternoon. I'll let you know when I have a fix.

Thanks again.

**Comment by Yortw** [comment]
Hi Scott,

I *think* I've fixed this. Just published a new Nuget package version, so if you want to try again with that and let me know if you're still having problems, that would be great.

Thanks.
