### ISSUE TITLE
Events on new password

### ISSUE THREAD

**Issue by ruisilva450** [Yortw/Yort.Otp#4]
Hi,

It would be nice to have a event handler for when the password changes.

**Comment by Yortw** [comment]
Thanks for the suggestion, but after some consideration I've decided not to implement this.

In the case of the CounterBasedPasswordGenerator the caller knows when it's changed. 

In the case of the TimeBasedPasswordGenerator an internal timer would be required, which would be disposable and therefore require TimeBasedPasswordGenerator to be disposable. This is technically a breaking change and makes the API uglier for consumers who don't care about it changing. 

The event seems largely pointless outside of client apps where possibly it might be useful for databinding/update of the views, but within server or auth library contexts the event does not seem useful.

In the case of a client app the app code itself should have no problem creating and raising the event itself. The app can either wrap the generators in a decorator that adds the event & requried timer/logic, or can just implement those things in it's view model. Four counter based generators the event can be raised each time the password is generated, and for time based generators the app can use the ValidUntilUtc to calculate the time the password will change and set it's own timer. The code to do this isn't very complex and only suits one intended use of the library.

Adding the event to the library doesn't at this time, to my thinking, seem to be a good idea.

I do appreciate the suggestion though.
